name: "\u2728 Feature Request"
description: Suggest a new feature or enhancement for Quotio
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions or features you've considered?
      placeholder: Other approaches you've thought about...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the app does this feature relate to?
      options:
        - New AI Provider Integration
        - New CLI Agent Support
        - Quota Tracking Enhancement
        - Dashboard / UI Improvement
        - Menu Bar Feature
        - Notification System
        - Proxy Server (CLIProxyAPI)
        - Settings / Configuration
        - Localization (new language)
        - Performance Optimization
        - Platform Support (Windows/Linux)
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      description: Help us prioritize features
      options:
        - "\U0001F534 Critical - Blocking my workflow"
        - "\U0001F7E0 High - Would significantly improve my experience"
        - "\U0001F7E1 Medium - Nice to have"
        - "\U0001F7E2 Low - Just an idea"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe how you would use this feature.
      placeholder: "As a [type of user], I want [feature] so that [benefit]..."
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If you have any mockups, screenshots from other apps, or examples, please attach them.
      placeholder: Drag and drop images here...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the feature request.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am willing to contribute to implementing this feature
          required: false
